name: "check"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ruff-check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
          cache: "pip"

      - name: "`pip install`"
        run: |
          pip install -r 'requirements.dev.txt'

      - name: "`ruff check`"
        run: |
          ruff check

  ruff-format:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
          cache: "pip"

      - name: "`pip install`"
        run: |
          pip install -r 'requirements.dev.txt'

      - name: "`ruff format`"
        run: |
          ruff format --check
