name: "daily-update"

on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  daily-update:
    runs-on: "ubuntu-latest"
    environment: "anidb"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.x"
          cache: "pip"

      - name: "Setup dependencies"
        run: |
          pip install -r requirements.txt

      - name: "Download `animetitles.json`"
        run: |
          mkdir -p 'data'

          (
            curl \
              --verbose \
              --fail --fail-early \
              'https://ddl.c032.dev/anidb/animetitles.json'
          ) > 'data/animetitles.json'

      - name: "Sanity check"
        run: |
          python check.py

      - name: "`git config`"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: 'Commit and push'
        run: |
          git add --all -v
          git commit -m 'Daily update'
          git push origin main
